FROM java:8


#RUN yum install -y openssh-clients

WORKDIR /apphome

ARG JAR_FILE

#COPY ${JAR_FILE}  .

COPY docker-allinone .



#COPY build/libs .

RUN echo "jar-->"${JAR_FILE}

EXPOSE 8080
ENV TZ "Asia/Shanghai"
ENV LIB_JARS=/apphome/saturn-executor-3.3.1/lib/*:$CLASSPATH
RUN ["chmod", "+x", "/apphome/run.sh"]

CMD ["/apphome/run.sh"]

#ENV jarPath=${JAR_FILE}

# java,product environment and other

#ENV JAVA_CMD="/usr/local/openjdk-8/bin/java -jar  -XX:-OmitStackTraceInFastThrow -Dserver.port=8080 -Dauthentication.enabled=true -Dauthorization.enabled.default=true ${JAR_FILE}  "
#ENV JAVA_CMD_PRO="/apphome/saturn-executor-3.3.1/bin/saturn-executor.sh  start -n jobcenter.erp.wms   -jmx 8080"


#ENTRYPOINT ["/tini", "--", "/bin/sh", "-c", "if [ ${SPRING_PROFILES_ACTIVE} = 'pro' ] ; then $JAVA_CMD_PRO ;else $JAVA_CMD ;fi"]


