kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: jobcenter-saturn-executor   #唯一
  namespace: component
spec:
  replicas: 1
  selector:
    matchLabels: # @1 要匹配的标签,与@2 要保持一致
      app: jobcenter-saturn-executor
  strategy:
    rollingUpdate:
      maxSurge: 1      #滚动升级时会先启动1个pod。这个值可以设置为整数和百分比,如果是使用百分比，则使用向上取整 参考 java.lang.Math.ceil
      maxUnavailable: 1 #滚动升级时允许的最大Unavailable的pod个数。这个值可以使用整数和百分比，如果是使用百分比，则向下取整数， 参考 java.lang.Math.floor
  template:
    metadata:
      labels:
        app: jobcenter-saturn-executor # @2 与上面 @1 要保持一致
    spec:
      containers:
        - name: jobcenter-saturn-executor #容器名称, 在一个pod中是唯一的
          image: harbor.34580.com/erp/jobcenter-saturn-executor/jobcenter-saturn-executor:24 # Docker镜像名称
          imagePullPolicy: Always  #镜像拉取策略,Always | Never | IfNotPersent，默认 Always
          # command:
          #   - sleep
          #   - "6000"
          volumeMounts:

          - mountPath: /apps
            name: test-volume

          ports:
            - name: port1
              containerPort: 8080
            #  hostIP: 0.0.0.0　　　　　
            #  hostPort: 58000
              protocol: TCP
          env:
            - name: MY_APP_HOSTIP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP


            - name: VIP_SATURN_CONSOLE_URI
              value: http://10.1.62.170:19991

            - name: SPRING_PROFILES_ACTIVE
              value: pro

      volumes:
        - name: test-volume
          hostPath:
            path: /apps2


